### ISSUE TITLE
Jede vierte Taste liefert immer die volle Anschlagstärke

### ISSUE THREAD

**Issue by rfeld** [birgitfeld/pianoRevial#2]
Von unten an gezählt liefert jede Vierte Taste (tiefstes C, tiefstes E, ...) scheinbar unabhängig von der Anschlagstärke immer die volle Velocity von 127.
Testaufbau: Alle "Sense"-Leitungen und die ersten vier "klingelleitungen" angeschlossen.
Version: Die vom ersten Pull-Request.

**Comment by birgitfeld** [comment]
Hardware issue -> solved
